cuenca-mx/cuenca-python

.github/workflows/release.yml
=> using push instead of release

.github/workflows/release.yml
=> add __token__

Makefile, README.md, cuenca/resources/transfers.py, cuenca/validators.py, cuenca/version.py, examples/batch_transfers.py, tests/resources/cassettes/test_transfers_create_many.yaml, tests/resources/test_transfers.py
- closes #6 by supporting a payment card for `Transfer.account_number`
- adds `Transfer.create_many()` for doing batch creates
=> Payment card

cuenca/resources/transfers.py, examples/batch_transfers.py, tests/resources/cassettes/test_transfers_create_many.yaml, tests/resources/test_transfers.py
This solves the issue of [examples/batch_transfers.py](https://github.com/cuenca-mx/cuenca-python/blob/create_many/examples/batch_transfers.py) failing if a single transfer fails.
=> more robust implementation of Transfer.create_many

cuenca/version.py, setup.py
change `QueryParams.user` to `QueryParams.user_id`
=> change QueryParams.user to QueryParams.user_id

.github/dependabot.yml, Makefile, cuenca/version.py, requirements-test.txt, requirements.txt, setup.py
=> Cambios en requirements

cuenca/resources/base.py, cuenca/version.py, tests/resources/cassettes/test_transfers_all.yaml, tests/resources/cassettes/test_transfers_count_vs_all.yaml, tests/resources/cassettes/test_transfers_first.yaml, tests/resources/cassettes/test_transfers_one.yaml, tests/resources/cassettes/test_transfers_one_errors.yaml
=> next_page_url=>_url

cuenca/resources/whatsapp_transfers.py
Changes correspond to the counterpart in oaxaca PR: https://github.com/cuenca-mx/oaxaca/pull/153
=> Whastapp transfer optional claim url

cuenca/resources/resources.py, cuenca/resources/transfers.py
Fix performance: Use TransferRequest of cuenca-validations and retrieve_uris
=> Use TransferRequest of cuenca-validations and retrieve_uris

cuenca/version.py, requirements.txt
new version cuenca-validations with fix in validator of statement.
=> bump version cuenca-validations

cuenca/resources/card_transactions.py
closes #114 114
issue oaxaca: https://github.com/cuenca-mx/oaxaca/pull/272
cuenca-validations: https://github.com/cuenca-mx/cuenca-validations/pull/109
=> Filter card_id with cuenca-validations

cuenca/resources/balance_entries.py, cuenca/version.py, requirements.txt, tests/resources/cassettes/test_query_balance_entry.yaml, tests/resources/test_balance_entries.py
Add filter for balance entries
related with: cuenca-mx/cuenca-validations#120
related with: https://github.com/cuenca-mx/oaxaca/pull/283
=> filter funding_instrument_uri in balance entries 

cuenca/version.py
Fix temporal debido a discrepancia en releases en github y versiones en Pypi.
Para arreglar 
Closes #150
Se crea issue #149 para arreglar 0.7.5
=> Bumping version to 0.7.6

cuenca/resources/card_validations.py, cuenca/version.py, requirements.txt, tests/resources/cassettes/test_card_validations.yaml, tests/resources/test_card_validations.py
=> pin_tries in card_validations

cuenca/version.py, requirements-test.txt, setup.py
This PR bumps `cuenca-validations` version
=> Compatible cv

cuenca/version.py, requirements.txt
This CV version allows people without 2 names to create `LimitedWallets`
=> New cv version

cuenca/resources/curp_validations.py, cuenca/version.py, requirements.txt
This PR will allow create a `CurpValidation` just with a `manual_curp`
=> CurpValidation v2

cuenca/resources/kyc_verifications.py, cuenca/version.py, requirements.txt, tests/resources/cassettes/test_kyc_verification_update.yaml, tests/resources/test_kyc_verifications.py
This PR adds the possibility to update `curp` or `rfc` from the `KYCVerification` resource
- related https://github.com/cuenca-mx/cuenca-validations/pull/239
=> Update kyc curp

cuenca/version.py, requirements.txt, tests/resources/cassettes/test_user_query_all_identity_id.yaml, tests/resources/cassettes/test_user_query_by_identity_id.yaml, tests/resources/test_users.py
This PR adds `identity_id` as query param for `User` resource
- closes #270
- related https://github.com/cuenca-mx/cuenca-validations/pull/247
- related https://github.com/cuenca-mx/identify/pull/113
=> Making user queryable by identity_id

cuenca/resources/transfers.py, cuenca/resources/users.py, cuenca/version.py, requirements.txt, tests/resources/cassettes/test_user_create.yaml, tests/resources/cassettes/test_user_fetch_balance.yaml, tests/resources/test_users.py
- Allow create transfers passing `user_id` as param
- Add `clabe` field  in User
- Add `balance` property in User
=> Add user_id  to create transfers

cuenca/resources/curp_validations.py, cuenca/resources/users.py, cuenca/version.py, requirements.txt
This PR adds `identity_id` as query param for `User` resource
- closes #281
- related https://github.com/cuenca-mx/cuenca-validations/pull/255
=> Add user status on create 

cuenca/resources/user_credentials.py, cuenca/resources/user_logins.py, cuenca/version.py, requirements.txt
Now, we can send `user_id` when creating password and login
=> UserCredentials and UserLogin with `user_id`

cuenca/resources/users.py, cuenca/version.py, requirements.txt
Make updateable the `UserStatus`
=> Update user status

cuenca/version.py, requirements.txt
=> Open passwords

cuenca/version.py, requirements.txt
=> Allowing `account_entries` SessionType

cuenca/resources/endpoints.py, cuenca/version.py, tests/resources/cassettes/test_endpoint_update.yaml, tests/resources/test_endpoints.py
Adding events field in Endpoint update method.
=> Events in endpoints update

.github/workflows/test.yml, cuenca/version.py, requirements.txt
=> Session files cv

cuenca/version.py, requirements.txt
New error when somebody is trying to request from a different location
=> Localization Error
